<?php

namespace ContainerOtxXfuk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FENMkGQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FENMkGQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FENMkGQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FavorisController::index' => ['privates', '.service_locator.M.WXHx5', 'get_ServiceLocator_M_WXHx5Service', true],
            'App\\Controller\\PostController::batiment' => ['privates', '.service_locator.ZPBLb9P', 'get_ServiceLocator_ZPBLb9PService', true],
            'App\\Controller\\PostController::bois' => ['privates', '.service_locator.ZPBLb9P', 'get_ServiceLocator_ZPBLb9PService', true],
            'App\\Controller\\PostController::create' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\PostController::edit' => ['privates', '.service_locator.Sq6qDTV', 'get_ServiceLocator_Sq6qDTVService', true],
            'App\\Controller\\PostController::exploitation' => ['privates', '.service_locator.ZPBLb9P', 'get_ServiceLocator_ZPBLb9PService', true],
            'App\\Controller\\PostController::index' => ['privates', '.service_locator.ZPBLb9P', 'get_ServiceLocator_ZPBLb9PService', true],
            'App\\Controller\\PostController::prairie' => ['privates', '.service_locator.ZPBLb9P', 'get_ServiceLocator_ZPBLb9PService', true],
            'App\\Controller\\PostController::show' => ['privates', '.service_locator.M.WXHx5', 'get_ServiceLocator_M_WXHx5Service', true],
            'App\\Controller\\PostController::terrain' => ['privates', '.service_locator.ZPBLb9P', 'get_ServiceLocator_ZPBLb9PService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.TFL26QP', 'get_ServiceLocator_TFL26QPService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\FavorisController:index' => ['privates', '.service_locator.M.WXHx5', 'get_ServiceLocator_M_WXHx5Service', true],
            'App\\Controller\\PostController:batiment' => ['privates', '.service_locator.ZPBLb9P', 'get_ServiceLocator_ZPBLb9PService', true],
            'App\\Controller\\PostController:bois' => ['privates', '.service_locator.ZPBLb9P', 'get_ServiceLocator_ZPBLb9PService', true],
            'App\\Controller\\PostController:create' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\PostController:edit' => ['privates', '.service_locator.Sq6qDTV', 'get_ServiceLocator_Sq6qDTVService', true],
            'App\\Controller\\PostController:exploitation' => ['privates', '.service_locator.ZPBLb9P', 'get_ServiceLocator_ZPBLb9PService', true],
            'App\\Controller\\PostController:index' => ['privates', '.service_locator.ZPBLb9P', 'get_ServiceLocator_ZPBLb9PService', true],
            'App\\Controller\\PostController:prairie' => ['privates', '.service_locator.ZPBLb9P', 'get_ServiceLocator_ZPBLb9PService', true],
            'App\\Controller\\PostController:show' => ['privates', '.service_locator.M.WXHx5', 'get_ServiceLocator_M_WXHx5Service', true],
            'App\\Controller\\PostController:terrain' => ['privates', '.service_locator.ZPBLb9P', 'get_ServiceLocator_ZPBLb9PService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.TFL26QP', 'get_ServiceLocator_TFL26QPService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\FavorisController::index' => '?',
            'App\\Controller\\PostController::batiment' => '?',
            'App\\Controller\\PostController::bois' => '?',
            'App\\Controller\\PostController::create' => '?',
            'App\\Controller\\PostController::edit' => '?',
            'App\\Controller\\PostController::exploitation' => '?',
            'App\\Controller\\PostController::index' => '?',
            'App\\Controller\\PostController::prairie' => '?',
            'App\\Controller\\PostController::show' => '?',
            'App\\Controller\\PostController::terrain' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FavorisController:index' => '?',
            'App\\Controller\\PostController:batiment' => '?',
            'App\\Controller\\PostController:bois' => '?',
            'App\\Controller\\PostController:create' => '?',
            'App\\Controller\\PostController:edit' => '?',
            'App\\Controller\\PostController:exploitation' => '?',
            'App\\Controller\\PostController:index' => '?',
            'App\\Controller\\PostController:prairie' => '?',
            'App\\Controller\\PostController:show' => '?',
            'App\\Controller\\PostController:terrain' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
