<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOlSPLTT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOlSPLTT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOlSPLTT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOlSPLTT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOlSPLTT\App_KernelDevDebugContainer([
    'container.build_hash' => 'OlSPLTT',
    'container.build_id' => '6beff1ea',
    'container.build_time' => 1673206277,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOlSPLTT');
